name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build -r --verbose
      - name: Run tests
        run: cargo test --verbose
      - uses: actions/upload-artifact@v3
        name: Upload artifacts
        with:
          name: Release
          path: target/release/proxymate
